{% raw %}alias: EMHASS Sigenergy Battery Management
description: "Automatically control the Sigenergy battery system using the EMHASS energy plan"
triggers:
  - trigger: state
    entity_id:
      - sensor.mpc_batt_power
      - sensor.mpc_grid_power
    from: null
    to: null
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - variables:
      p_batt: "{{ states('sensor.mpc_batt_power') | int(0) }}"
      p_batt_kw: "{{ (p_batt / 1000) | round(3) }}"
      p_grid: "{{ states('sensor.mpc_grid_power') | int(0) }}"
      max_charge_rate: "{{ states('sensor.sigen_plant_ess_rated_charging_power') | float(0) }}"
      max_discharge_rate: "{{ states('sensor.sigen_plant_ess_rated_discharging_power') | float(0) }}"
      max_import_rate_kw: 100
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ p_grid == 0 }}"
        sequence:
          - action: select.select_option
            metadata: {}
            data:
              option: Maximum Self Consumption
            target:
              entity_id: select.sigen_plant_remote_ems_control_mode
            alias: Maximum Self Consumption
          - action: number.set_value
            metadata: {}
            data:
              value: "{{ max_charge_rate }}"
            target:
              entity_id:
                - number.sigen_plant_ess_max_charging_limit
          - action: number.set_value
            metadata: {}
            data:
              value: "{{ max_discharge_rate }}"
            target:
              entity_id:
                - number.sigen_plant_ess_max_discharging_limit
        alias: Check self consume conditions
      - conditions:
          - condition: template
            value_template: "{{ p_batt > 0 or (p_grid < 0 and p_batt == 0) }}"
        sequence:
          - action: select.select_option
            metadata: {}
            data:
              option: Command Discharging (PV First)
            target:
              entity_id: select.sigen_plant_remote_ems_control_mode
          - action: number.set_value
            metadata: {}
            data:
              value: "{{ p_batt_kw }}"
            target:
              entity_id: number.sigen_plant_ess_max_discharging_limit
        alias: Check discharge conditions
      - conditions:
          - condition: template
            value_template: "{{ p_batt < 0 }}"
        sequence:
          - action: select.select_option
            metadata: {}
            data:
              option: Command Charging (PV First)
            target:
              entity_id: select.sigen_plant_remote_ems_control_mode
          - action: number.set_value
            metadata: {}
            data:
              value: "{{ p_batt_kw | abs }}"
            target:
              entity_id:
                - number.sigen_plant_ess_max_charging_limit
          - action: number.set_value
            metadata: {}
            data:
              value: "{{ max_import_rate_kw if p_grid > 0 else 0 }}"
            target:
              entity_id:
                - number.sigen_plant_pcs_import_limitation
        alias: Check charge conditions
      - conditions:
          - condition: template
            value_template: "{{ p_batt == 0 }}"
        sequence:
          - action: select.select_option
            metadata: {}
            data:
              option: Standby
            target:
              entity_id: select.sigen_plant_remote_ems_control_mode
          - action: number.set_value
            metadata: {}
            data:
              value: 0
            target:
              entity_id:
                - number.sigen_plant_pcs_import_limitation
        alias: Check standby conditions
mode: single{% endraw %}
